package com.hbsi.domain;

import java.io.Serializable;

public class BreakConclusion implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column break_conclusion.id
     *
     * @mbg.generated Thu Dec 06 17:20:36 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column break_conclusion.entrustment_number
     *
     * @mbg.generated Thu Dec 06 17:20:36 CST 2018
     */
    private String entrustmentNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column break_conclusion.n_diamete
     *
     * @mbg.generated Thu Dec 06 17:20:36 CST 2018
     */
    private Double nDiamete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column break_conclusion.steel_number
     *
     * @mbg.generated Thu Dec 06 17:20:36 CST 2018
     */
    private Integer steelNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column break_conclusion.standard_strength
     *
     * @mbg.generated Thu Dec 06 17:20:36 CST 2018
     */
    private Integer standardStrength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column break_conclusion.standard_diameter
     *
     * @mbg.generated Thu Dec 06 17:20:36 CST 2018
     */
    private String standardDiameter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column break_conclusion.measure_diameter
     *
     * @mbg.generated Thu Dec 06 17:20:36 CST 2018
     */
    private String measureDiameter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column break_conclusion.standard_tensile
     *
     * @mbg.generated Thu Dec 06 17:20:36 CST 2018
     */
    private String standardTensile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column break_conclusion.measure_tensile
     *
     * @mbg.generated Thu Dec 06 17:20:36 CST 2018
     */
    private String measureTensile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column break_conclusion.standard_knot
     *
     * @mbg.generated Thu Dec 06 17:20:36 CST 2018
     */
    private String standardKnot;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column break_conclusion.measure_knot
     *
     * @mbg.generated Thu Dec 06 17:20:36 CST 2018
     */
    private String measureKnot;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column break_conclusion.standard_reverse
     *
     * @mbg.generated Thu Dec 06 17:20:36 CST 2018
     */
    private String standardReverse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column break_conclusion.measure_reverse
     *
     * @mbg.generated Thu Dec 06 17:20:36 CST 2018
     */
    private String measureReverse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column break_conclusion.standard_bending
     *
     * @mbg.generated Thu Dec 06 17:20:36 CST 2018
     */
    private String standardBending;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column break_conclusion.measure_bending
     *
     * @mbg.generated Thu Dec 06 17:20:36 CST 2018
     */
    private String measureBending;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column break_conclusion.standard_zinc
     *
     * @mbg.generated Thu Dec 06 17:20:36 CST 2018
     */
    private String standardZinc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column break_conclusion.measure_zinc
     *
     * @mbg.generated Thu Dec 06 17:20:36 CST 2018
     */
    private String measureZinc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column break_conclusion.state
     *
     * @mbg.generated Thu Dec 06 17:20:36 CST 2018
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table break_conclusion
     *
     * @mbg.generated Thu Dec 06 17:20:36 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column break_conclusion.id
     *
     * @return the value of break_conclusion.id
     *
     * @mbg.generated Thu Dec 06 17:20:36 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column break_conclusion.id
     *
     * @param id the value for break_conclusion.id
     *
     * @mbg.generated Thu Dec 06 17:20:36 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column break_conclusion.entrustment_number
     *
     * @return the value of break_conclusion.entrustment_number
     *
     * @mbg.generated Thu Dec 06 17:20:36 CST 2018
     */
    public String getEntrustmentNumber() {
        return entrustmentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column break_conclusion.entrustment_number
     *
     * @param entrustmentNumber the value for break_conclusion.entrustment_number
     *
     * @mbg.generated Thu Dec 06 17:20:36 CST 2018
     */
    public void setEntrustmentNumber(String entrustmentNumber) {
        this.entrustmentNumber = entrustmentNumber == null ? null : entrustmentNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column break_conclusion.n_diamete
     *
     * @return the value of break_conclusion.n_diamete
     *
     * @mbg.generated Thu Dec 06 17:20:36 CST 2018
     */
    public Double getnDiamete() {
        return nDiamete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column break_conclusion.n_diamete
     *
     * @param nDiamete the value for break_conclusion.n_diamete
     *
     * @mbg.generated Thu Dec 06 17:20:36 CST 2018
     */
    public void setnDiamete(Double nDiamete) {
        this.nDiamete = nDiamete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column break_conclusion.steel_number
     *
     * @return the value of break_conclusion.steel_number
     *
     * @mbg.generated Thu Dec 06 17:20:36 CST 2018
     */
    public Integer getSteelNumber() {
        return steelNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column break_conclusion.steel_number
     *
     * @param steelNumber the value for break_conclusion.steel_number
     *
     * @mbg.generated Thu Dec 06 17:20:36 CST 2018
     */
    public void setSteelNumber(Integer steelNumber) {
        this.steelNumber = steelNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column break_conclusion.standard_strength
     *
     * @return the value of break_conclusion.standard_strength
     *
     * @mbg.generated Thu Dec 06 17:20:36 CST 2018
     */
    public Integer getStandardStrength() {
        return standardStrength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column break_conclusion.standard_strength
     *
     * @param standardStrength the value for break_conclusion.standard_strength
     *
     * @mbg.generated Thu Dec 06 17:20:36 CST 2018
     */
    public void setStandardStrength(Integer standardStrength) {
        this.standardStrength = standardStrength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column break_conclusion.standard_diameter
     *
     * @return the value of break_conclusion.standard_diameter
     *
     * @mbg.generated Thu Dec 06 17:20:36 CST 2018
     */
    public String getStandardDiameter() {
        return standardDiameter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column break_conclusion.standard_diameter
     *
     * @param standardDiameter the value for break_conclusion.standard_diameter
     *
     * @mbg.generated Thu Dec 06 17:20:36 CST 2018
     */
    public void setStandardDiameter(String standardDiameter) {
        this.standardDiameter = standardDiameter == null ? null : standardDiameter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column break_conclusion.measure_diameter
     *
     * @return the value of break_conclusion.measure_diameter
     *
     * @mbg.generated Thu Dec 06 17:20:36 CST 2018
     */
    public String getMeasureDiameter() {
        return measureDiameter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column break_conclusion.measure_diameter
     *
     * @param measureDiameter the value for break_conclusion.measure_diameter
     *
     * @mbg.generated Thu Dec 06 17:20:36 CST 2018
     */
    public void setMeasureDiameter(String measureDiameter) {
        this.measureDiameter = measureDiameter == null ? null : measureDiameter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column break_conclusion.standard_tensile
     *
     * @return the value of break_conclusion.standard_tensile
     *
     * @mbg.generated Thu Dec 06 17:20:36 CST 2018
     */
    public String getStandardTensile() {
        return standardTensile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column break_conclusion.standard_tensile
     *
     * @param standardTensile the value for break_conclusion.standard_tensile
     *
     * @mbg.generated Thu Dec 06 17:20:36 CST 2018
     */
    public void setStandardTensile(String standardTensile) {
        this.standardTensile = standardTensile == null ? null : standardTensile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column break_conclusion.measure_tensile
     *
     * @return the value of break_conclusion.measure_tensile
     *
     * @mbg.generated Thu Dec 06 17:20:36 CST 2018
     */
    public String getMeasureTensile() {
        return measureTensile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column break_conclusion.measure_tensile
     *
     * @param measureTensile the value for break_conclusion.measure_tensile
     *
     * @mbg.generated Thu Dec 06 17:20:36 CST 2018
     */
    public void setMeasureTensile(String measureTensile) {
        this.measureTensile = measureTensile == null ? null : measureTensile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column break_conclusion.standard_knot
     *
     * @return the value of break_conclusion.standard_knot
     *
     * @mbg.generated Thu Dec 06 17:20:36 CST 2018
     */
    public String getStandardKnot() {
        return standardKnot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column break_conclusion.standard_knot
     *
     * @param standardKnot the value for break_conclusion.standard_knot
     *
     * @mbg.generated Thu Dec 06 17:20:36 CST 2018
     */
    public void setStandardKnot(String standardKnot) {
        this.standardKnot = standardKnot == null ? null : standardKnot.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column break_conclusion.measure_knot
     *
     * @return the value of break_conclusion.measure_knot
     *
     * @mbg.generated Thu Dec 06 17:20:36 CST 2018
     */
    public String getMeasureKnot() {
        return measureKnot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column break_conclusion.measure_knot
     *
     * @param measureKnot the value for break_conclusion.measure_knot
     *
     * @mbg.generated Thu Dec 06 17:20:36 CST 2018
     */
    public void setMeasureKnot(String measureKnot) {
        this.measureKnot = measureKnot == null ? null : measureKnot.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column break_conclusion.standard_reverse
     *
     * @return the value of break_conclusion.standard_reverse
     *
     * @mbg.generated Thu Dec 06 17:20:36 CST 2018
     */
    public String getStandardReverse() {
        return standardReverse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column break_conclusion.standard_reverse
     *
     * @param standardReverse the value for break_conclusion.standard_reverse
     *
     * @mbg.generated Thu Dec 06 17:20:36 CST 2018
     */
    public void setStandardReverse(String standardReverse) {
        this.standardReverse = standardReverse == null ? null : standardReverse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column break_conclusion.measure_reverse
     *
     * @return the value of break_conclusion.measure_reverse
     *
     * @mbg.generated Thu Dec 06 17:20:36 CST 2018
     */
    public String getMeasureReverse() {
        return measureReverse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column break_conclusion.measure_reverse
     *
     * @param measureReverse the value for break_conclusion.measure_reverse
     *
     * @mbg.generated Thu Dec 06 17:20:36 CST 2018
     */
    public void setMeasureReverse(String measureReverse) {
        this.measureReverse = measureReverse == null ? null : measureReverse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column break_conclusion.standard_bending
     *
     * @return the value of break_conclusion.standard_bending
     *
     * @mbg.generated Thu Dec 06 17:20:36 CST 2018
     */
    public String getStandardBending() {
        return standardBending;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column break_conclusion.standard_bending
     *
     * @param standardBending the value for break_conclusion.standard_bending
     *
     * @mbg.generated Thu Dec 06 17:20:36 CST 2018
     */
    public void setStandardBending(String standardBending) {
        this.standardBending = standardBending == null ? null : standardBending.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column break_conclusion.measure_bending
     *
     * @return the value of break_conclusion.measure_bending
     *
     * @mbg.generated Thu Dec 06 17:20:36 CST 2018
     */
    public String getMeasureBending() {
        return measureBending;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column break_conclusion.measure_bending
     *
     * @param measureBending the value for break_conclusion.measure_bending
     *
     * @mbg.generated Thu Dec 06 17:20:36 CST 2018
     */
    public void setMeasureBending(String measureBending) {
        this.measureBending = measureBending == null ? null : measureBending.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column break_conclusion.standard_zinc
     *
     * @return the value of break_conclusion.standard_zinc
     *
     * @mbg.generated Thu Dec 06 17:20:36 CST 2018
     */
    public String getStandardZinc() {
        return standardZinc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column break_conclusion.standard_zinc
     *
     * @param standardZinc the value for break_conclusion.standard_zinc
     *
     * @mbg.generated Thu Dec 06 17:20:36 CST 2018
     */
    public void setStandardZinc(String standardZinc) {
        this.standardZinc = standardZinc == null ? null : standardZinc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column break_conclusion.measure_zinc
     *
     * @return the value of break_conclusion.measure_zinc
     *
     * @mbg.generated Thu Dec 06 17:20:36 CST 2018
     */
    public String getMeasureZinc() {
        return measureZinc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column break_conclusion.measure_zinc
     *
     * @param measureZinc the value for break_conclusion.measure_zinc
     *
     * @mbg.generated Thu Dec 06 17:20:36 CST 2018
     */
    public void setMeasureZinc(String measureZinc) {
        this.measureZinc = measureZinc == null ? null : measureZinc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column break_conclusion.state
     *
     * @return the value of break_conclusion.state
     *
     * @mbg.generated Thu Dec 06 17:20:36 CST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column break_conclusion.state
     *
     * @param state the value for break_conclusion.state
     *
     * @mbg.generated Thu Dec 06 17:20:36 CST 2018
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table break_conclusion
     *
     * @mbg.generated Thu Dec 06 17:20:36 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", entrustmentNumber=").append(entrustmentNumber);
        sb.append(", nDiamete=").append(nDiamete);
        sb.append(", steelNumber=").append(steelNumber);
        sb.append(", standardStrength=").append(standardStrength);
        sb.append(", standardDiameter=").append(standardDiameter);
        sb.append(", measureDiameter=").append(measureDiameter);
        sb.append(", standardTensile=").append(standardTensile);
        sb.append(", measureTensile=").append(measureTensile);
        sb.append(", standardKnot=").append(standardKnot);
        sb.append(", measureKnot=").append(measureKnot);
        sb.append(", standardReverse=").append(standardReverse);
        sb.append(", measureReverse=").append(measureReverse);
        sb.append(", standardBending=").append(standardBending);
        sb.append(", measureBending=").append(measureBending);
        sb.append(", standardZinc=").append(standardZinc);
        sb.append(", measureZinc=").append(measureZinc);
        sb.append(", state=").append(state);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}