package com.hbsi.domain;

import java.io.Serializable;
import java.sql.Timestamp;
import java.util.Date;

import org.nutz.castor.castor.Datetime2Timpestamp;

public class Entrustment implements Serializable {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column entrustment.id
	 *
	 * @mbg.generated Thu Sep 27 09:05:52 CST 2018
	 */
	private Integer id;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column entrustment.sample_batch
	 *
	 * @mbg.generated Thu Sep 27 09:05:52 CST 2018
	 */
	private Integer sampleBatch;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column entrustment.entrustment_number
	 *
	 * @mbg.generated Thu Sep 27 09:05:52 CST 2018
	 */
	private String entrustmentNumber;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column entrustment.state
	 *
	 * @mbg.generated Thu Sep 27 09:05:52 CST 2018
	 */
	private String state;
	/**
	 * 新加字段
	 */
	private Timestamp createTime;

	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table entrustment
	 *
	 * @mbg.generated Thu Sep 27 09:05:52 CST 2018
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column entrustment.id
	 *
	 * @return the value of entrustment.id
	 *
	 * @mbg.generated Thu Sep 27 09:05:52 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	public Integer getSampleBatch() {
		return sampleBatch;
	}

	public void setSampleBatch(Integer sampleBatch) {
		this.sampleBatch = sampleBatch;
	}

	public String getEntrustmentNumber() {
		return entrustmentNumber;
	}

	public void setEntrustmentNumber(String entrustmentNumber) {
		this.entrustmentNumber = entrustmentNumber;
	}

	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}


	public Timestamp getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Timestamp createTime) {
		this.createTime = createTime;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Override
	public String toString() {
		return "Entrustment [id=" + id + ", sampleBatch=" + sampleBatch + ", entrustmentNumber=" + entrustmentNumber
				+ ", state=" + state + ", createTime=" + createTime + "]";
	}

	
	

}