package com.hbsi.domain;

import java.io.Serializable;

public class Machine implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column machine.id
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column machine.machine_number
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    private Integer machineAddr;
    private String machineType;
    private String machineNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column machine.state
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table machine
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column machine.id
     *
     * @return the value of machine.id
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column machine.id
     *
     * @param id the value for machine.id
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getMachineAddr() {
		return machineAddr;
	}

	public void setMachineAddr(Integer machineAddr) {
		this.machineAddr = machineAddr;
	}

	public String getMachineType() {
		return machineType;
	}

	public void setMachineType(String machineType) {
		this.machineType = machineType;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column machine.machine_number
     *
     * @return the value of machine.machine_number
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public String getMachineNumber() {
        return machineNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column machine.machine_number
     *
     * @param machineNumber the value for machine.machine_number
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public void setMachineNumber(String machineNumber) {
        this.machineNumber = machineNumber == null ? null : machineNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column machine.state
     *
     * @return the value of machine.state
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column machine.state
     *
     * @param state the value for machine.state
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table machine
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", machineAddr=").append(machineAddr);
        sb.append(", machineType=").append(machineType);
        sb.append(", machineNumber=").append(machineNumber);
        sb.append(", state=").append(state);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}