package com.hbsi.domain;

import java.io.Serializable;

public class ReverseBending implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reverse_bending.id
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reverse_bending.machine_number
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
	private String standardNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reverse_bending.rated_strength
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    private String ratedStrength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reverse_bending.surface_state
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    private String surfaceState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reverse_bending.diamete_min
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    private Double diameteMin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reverse_bending.diamete_max
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    private Double diameteMax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reverse_bending.value_rob
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    private Integer valueRob;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reverse_bending.type
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reverse_bending.state
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    private String state;
    private String usage;
    private Double fDiamete;
    private Integer rob;
    /**
     * 钢丝类别，例如  面接触钢丝
     */
    private String wireClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table reverse_bending
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reverse_bending.id
     *
     * @return the value of reverse_bending.id
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reverse_bending.id
     *
     * @param id the value for reverse_bending.id
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reverse_bending.machine_number
     *
     * @return the value of reverse_bending.machine_number
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public String getStandardNum() {
        return standardNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reverse_bending.machine_number
     *
     * @param standardNum the value for reverse_bending.machine_number
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public void setStandardNum(String standardNum) {
        this.standardNum = standardNum == null ? null : standardNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reverse_bending.rated_strength
     *
     * @return the value of reverse_bending.rated_strength
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public String getRatedStrength() {
        return ratedStrength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reverse_bending.rated_strength
     *
     * @param ratedStrength the value for reverse_bending.rated_strength
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public void setRatedStrength(String ratedStrength) {
        this.ratedStrength = ratedStrength == null ? null : ratedStrength.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reverse_bending.surface_state
     *
     * @return the value of reverse_bending.surface_state
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public String getSurfaceState() {
        return surfaceState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reverse_bending.surface_state
     *
     * @param surfaceState the value for reverse_bending.surface_state
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public void setSurfaceState(String surfaceState) {
        this.surfaceState = surfaceState == null ? null : surfaceState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reverse_bending.diamete_min
     *
     * @return the value of reverse_bending.diamete_min
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public Double getDiameteMin() {
        return diameteMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reverse_bending.diamete_min
     *
     * @param diameteMin the value for reverse_bending.diamete_min
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public void setDiameteMin(Double diameteMin) {
        this.diameteMin = diameteMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reverse_bending.diamete_max
     *
     * @return the value of reverse_bending.diamete_max
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public Double getDiameteMax() {
        return diameteMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reverse_bending.diamete_max
     *
     * @param diameteMax the value for reverse_bending.diamete_max
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public void setDiameteMax(Double diameteMax) {
        this.diameteMax = diameteMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reverse_bending.value_rob
     *
     * @return the value of reverse_bending.value_rob
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public Integer getValueRob() {
        return valueRob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reverse_bending.value_rob
     *
     * @param valueRob the value for reverse_bending.value_rob
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public void setValueRob(Integer valueRob) {
        this.valueRob = valueRob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reverse_bending.type
     *
     * @return the value of reverse_bending.type
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reverse_bending.type
     *
     * @param type the value for reverse_bending.type
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reverse_bending.state
     *
     * @return the value of reverse_bending.state
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reverse_bending.state
     *
     * @param state the value for reverse_bending.state
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    public String getUsage() {
		return usage;
	}

	public void setUsage(String usage) {
		this.usage = usage;
	}

	public Double getfDiamete() {
		return fDiamete;
	}

	public void setfDiamete(Double fDiamete) {
		this.fDiamete = fDiamete;
	}

	public Integer getRob() {
		return rob;
	}

	public void setRob(Integer rob) {
		this.rob = rob;
	}
	
	

	public String getWireClass() {
		return wireClass;
	}

	public void setWireClass(String wireClass) {
		this.wireClass = wireClass;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reverse_bending
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", standardNum=").append(standardNum);
        sb.append(", ratedStrength=").append(ratedStrength);
        sb.append(", surfaceState=").append(surfaceState);
        sb.append(", diameteMin=").append(diameteMin);
        sb.append(", diameteMax=").append(diameteMax);
        sb.append(", valueRob=").append(valueRob);
        sb.append(", type=").append(type);
        sb.append(", state=").append(state);
        sb.append(", usage=").append(usage);
        sb.append(", fDiamete=").append(fDiamete);
        sb.append(", rob=").append(rob);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}