package com.hbsi.domain;

import java.io.Serializable;

public class TensileStrength implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tensile_strength.id
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tensile_strength.machine_number
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    private String standardNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tensile_strength.strength_value
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    private Integer strengthValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tensile_strength.rated_strength
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    private Integer ratedStrength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tensile_strength.type
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tensile_strength.state
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tensile_strength
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tensile_strength.id
     *
     * @return the value of tensile_strength.id
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tensile_strength.id
     *
     * @param id the value for tensile_strength.id
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }


    public String getStandardNum() {
		return standardNum;
	}

	public void setStandardNum(String standardNum) {
		this.standardNum = standardNum;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tensile_strength.strength_value
     *
     * @return the value of tensile_strength.strength_value
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public Integer getStrengthValue() {
        return strengthValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tensile_strength.strength_value
     *
     * @param strengthValue the value for tensile_strength.strength_value
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public void setStrengthValue(Integer strengthValue) {
        this.strengthValue = strengthValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tensile_strength.rated_strength
     *
     * @return the value of tensile_strength.rated_strength
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public Integer getRatedStrength() {
        return ratedStrength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tensile_strength.rated_strength
     *
     * @param ratedStrength the value for tensile_strength.rated_strength
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public void setRatedStrength(Integer ratedStrength) {
        this.ratedStrength = ratedStrength ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tensile_strength.type
     *
     * @return the value of tensile_strength.type
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tensile_strength.type
     *
     * @param type the value for tensile_strength.type
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tensile_strength.state
     *
     * @return the value of tensile_strength.state
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tensile_strength.state
     *
     * @param state the value for tensile_strength.state
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }
    
    
    

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tensile_strength
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", standardNum=").append(standardNum);
        sb.append(", strengthValue=").append(strengthValue);
        sb.append(", ratedStrength=").append(ratedStrength);
        sb.append(", type=").append(type);
        sb.append(", state=").append(state);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}