package com.hbsi.domain;

import java.io.Serializable;

public class VersonNumber implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verson_number.id
     *
     * @mbg.generated Thu Dec 20 17:23:31 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verson_number.report_category
     *
     * @mbg.generated Thu Dec 20 17:23:31 CST 2018
     */
    private String reportCategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verson_number.verson_number
     *
     * @mbg.generated Thu Dec 20 17:23:31 CST 2018
     */
    private String versonNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verson_number.state
     *
     * @mbg.generated Thu Dec 20 17:23:31 CST 2018
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table verson_number
     *
     * @mbg.generated Thu Dec 20 17:23:31 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verson_number.id
     *
     * @return the value of verson_number.id
     *
     * @mbg.generated Thu Dec 20 17:23:31 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verson_number.id
     *
     * @param id the value for verson_number.id
     *
     * @mbg.generated Thu Dec 20 17:23:31 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verson_number.report_category
     *
     * @return the value of verson_number.report_category
     *
     * @mbg.generated Thu Dec 20 17:23:31 CST 2018
     */
    public String getReportCategory() {
        return reportCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verson_number.report_category
     *
     * @param reportCategory the value for verson_number.report_category
     *
     * @mbg.generated Thu Dec 20 17:23:31 CST 2018
     */
    public void setReportCategory(String reportCategory) {
        this.reportCategory = reportCategory == null ? null : reportCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verson_number.verson_number
     *
     * @return the value of verson_number.verson_number
     *
     * @mbg.generated Thu Dec 20 17:23:31 CST 2018
     */
    public String getVersonNumber() {
        return versonNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verson_number.verson_number
     *
     * @param versonNumber the value for verson_number.verson_number
     *
     * @mbg.generated Thu Dec 20 17:23:31 CST 2018
     */
    public void setVersonNumber(String versonNumber) {
        this.versonNumber = versonNumber == null ? null : versonNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verson_number.state
     *
     * @return the value of verson_number.state
     *
     * @mbg.generated Thu Dec 20 17:23:31 CST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verson_number.state
     *
     * @param state the value for verson_number.state
     *
     * @mbg.generated Thu Dec 20 17:23:31 CST 2018
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verson_number
     *
     * @mbg.generated Thu Dec 20 17:23:31 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", reportCategory=").append(reportCategory);
        sb.append(", versonNumber=").append(versonNumber);
        sb.append(", state=").append(state);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}