package com.hbsi.domain;

import java.io.Serializable;

public class WireStandard implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wire_standard.id
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wire_standard.standard_number
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    private String standardNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wire_standard.wire_table
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    private String wireTable;
    private String proName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wire_standard.state
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wire_standard
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wire_standard.id
     *
     * @return the value of wire_standard.id
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wire_standard.id
     *
     * @param id the value for wire_standard.id
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wire_standard.standard_number
     *
     * @return the value of wire_standard.standard_number
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public String getStandardNumber() {
        return standardNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wire_standard.standard_number
     *
     * @param standardNumber the value for wire_standard.standard_number
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public void setStandardNumber(String standardNumber) {
        this.standardNumber = standardNumber == null ? null : standardNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wire_standard.wire_table
     *
     * @return the value of wire_standard.wire_table
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public String getWireTable() {
        return wireTable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wire_standard.wire_table
     *
     * @param wireTable the value for wire_standard.wire_table
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public void setWireTable(String wireTable) {
        this.wireTable = wireTable == null ? null : wireTable.trim();
    }

    public String getProName() {
		return proName;
	}

	public void setProName(String proName) {
		this.proName = proName;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wire_standard.state
     *
     * @return the value of wire_standard.state
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wire_standard.state
     *
     * @param state the value for wire_standard.state
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wire_standard
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", standardNumber=").append(standardNumber);
        sb.append(", wireTable=").append(wireTable);
        sb.append(", state=").append(state);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}