package com.hbsi.domain;

import java.io.Serializable;

public class WireAttributesGBT89182006 implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wire_attributes_gbt8918_2006.id
     *
     * @mbg.generated Wed Oct 31 11:15:14 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wire_attributes_gbt8918_2006.classification
     *
     * @mbg.generated Wed Oct 31 11:15:14 CST 2018
     */
    private String classification;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wire_attributes_gbt8918_2006.structure
     *
     * @mbg.generated Wed Oct 31 11:15:14 CST 2018
     */
    private String structure;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wire_attributes_gbt8918_2006.minimum_breaking_force
     *
     * @mbg.generated Wed Oct 31 11:15:14 CST 2018
     */
    private Double minimumBreakingForce;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wire_attributes_gbt8918_2006.tanning_loss_factor
     *
     * @mbg.generated Wed Oct 31 11:15:14 CST 2018
     */
    private Double tanningLossFactor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wire_attributes_gbt8918_2006.state
     *
     * @mbg.generated Wed Oct 31 11:15:14 CST 2018
     */
    private String state;
    private double diamateMin;
    private double diamateMax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wire_attributes_gbt8918_2006
     *
     * @mbg.generated Wed Oct 31 11:15:14 CST 2018
     */
    private static final long serialVersionUID = 1L;
    
    private String shape;
    

    public String getShape() {
		return shape;
	}

	public void setShape(String shape) {
		this.shape = shape;
	}
	
	
	public double getDiamateMin() {
		return diamateMin;
	}

	public void setDiamateMin(double diamateMin) {
		this.diamateMin = diamateMin;
	}

	public double getDiamateMax() {
		return diamateMax;
	}

	public void setDiamateMax(double diamateMax) {
		this.diamateMax = diamateMax;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wire_attributes_gbt8918_2006.id
     *
     * @return the value of wire_attributes_gbt8918_2006.id
     *
     * @mbg.generated Wed Oct 31 11:15:14 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wire_attributes_gbt8918_2006.id
     *
     * @param id the value for wire_attributes_gbt8918_2006.id
     *
     * @mbg.generated Wed Oct 31 11:15:14 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wire_attributes_gbt8918_2006.classification
     *
     * @return the value of wire_attributes_gbt8918_2006.classification
     *
     * @mbg.generated Wed Oct 31 11:15:14 CST 2018
     */
    public String getClassification() {
        return classification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wire_attributes_gbt8918_2006.classification
     *
     * @param classification the value for wire_attributes_gbt8918_2006.classification
     *
     * @mbg.generated Wed Oct 31 11:15:14 CST 2018
     */
    public void setClassification(String classification) {
        this.classification = classification == null ? null : classification.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wire_attributes_gbt8918_2006.structure
     *
     * @return the value of wire_attributes_gbt8918_2006.structure
     *
     * @mbg.generated Wed Oct 31 11:15:14 CST 2018
     */
    public String getStructure() {
        return structure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wire_attributes_gbt8918_2006.structure
     *
     * @param structure the value for wire_attributes_gbt8918_2006.structure
     *
     * @mbg.generated Wed Oct 31 11:15:14 CST 2018
     */
    public void setStructure(String structure) {
        this.structure = structure == null ? null : structure.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wire_attributes_gbt8918_2006.minimum_breaking_force
     *
     * @return the value of wire_attributes_gbt8918_2006.minimum_breaking_force
     *
     * @mbg.generated Wed Oct 31 11:15:14 CST 2018
     */
    public Double getMinimumBreakingForce() {
        return minimumBreakingForce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wire_attributes_gbt8918_2006.minimum_breaking_force
     *
     * @param minimumBreakingForce the value for wire_attributes_gbt8918_2006.minimum_breaking_force
     *
     * @mbg.generated Wed Oct 31 11:15:14 CST 2018
     */
    public void setMinimumBreakingForce(Double minimumBreakingForce) {
        this.minimumBreakingForce = minimumBreakingForce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wire_attributes_gbt8918_2006.tanning_loss_factor
     *
     * @return the value of wire_attributes_gbt8918_2006.tanning_loss_factor
     *
     * @mbg.generated Wed Oct 31 11:15:14 CST 2018
     */
    public Double getTanningLossFactor() {
        return tanningLossFactor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wire_attributes_gbt8918_2006.tanning_loss_factor
     *
     * @param tanningLossFactor the value for wire_attributes_gbt8918_2006.tanning_loss_factor
     *
     * @mbg.generated Wed Oct 31 11:15:14 CST 2018
     */
    public void setTanningLossFactor(Double tanningLossFactor) {
        this.tanningLossFactor = tanningLossFactor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wire_attributes_gbt8918_2006.state
     *
     * @return the value of wire_attributes_gbt8918_2006.state
     *
     * @mbg.generated Wed Oct 31 11:15:14 CST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wire_attributes_gbt8918_2006.state
     *
     * @param state the value for wire_attributes_gbt8918_2006.state
     *
     * @mbg.generated Wed Oct 31 11:15:14 CST 2018
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wire_attributes_gbt8918_2006
     *
     * @mbg.generated Wed Oct 31 11:15:14 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", classification=").append(classification);
        sb.append(", structure=").append(structure);
        sb.append(", minimumBreakingForce=").append(minimumBreakingForce);
        sb.append(", tanningLossFactor=").append(tanningLossFactor);
        sb.append(", state=").append(state);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}