package com.hbsi.domain;

import java.io.Serializable;

public class WireAttributesYbt45422016 implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wire_attributes_ybt4542_2016.id
     *
     * @mbg.generated Fri Feb 15 10:54:03 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wire_attributes_ybt4542_2016.structure
     *
     * @mbg.generated Fri Feb 15 10:54:03 CST 2019
     */
    private String structure;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wire_attributes_ybt4542_2016.state
     *
     * @mbg.generated Fri Feb 15 10:54:03 CST 2019
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wire_attributes_ybt4542_2016
     *
     * @mbg.generated Fri Feb 15 10:54:03 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wire_attributes_ybt4542_2016.id
     *
     * @return the value of wire_attributes_ybt4542_2016.id
     *
     * @mbg.generated Fri Feb 15 10:54:03 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wire_attributes_ybt4542_2016.id
     *
     * @param id the value for wire_attributes_ybt4542_2016.id
     *
     * @mbg.generated Fri Feb 15 10:54:03 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wire_attributes_ybt4542_2016.structure
     *
     * @return the value of wire_attributes_ybt4542_2016.structure
     *
     * @mbg.generated Fri Feb 15 10:54:03 CST 2019
     */
    public String getStructure() {
        return structure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wire_attributes_ybt4542_2016.structure
     *
     * @param structure the value for wire_attributes_ybt4542_2016.structure
     *
     * @mbg.generated Fri Feb 15 10:54:03 CST 2019
     */
    public void setStructure(String structure) {
        this.structure = structure == null ? null : structure.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wire_attributes_ybt4542_2016.state
     *
     * @return the value of wire_attributes_ybt4542_2016.state
     *
     * @mbg.generated Fri Feb 15 10:54:03 CST 2019
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wire_attributes_ybt4542_2016.state
     *
     * @param state the value for wire_attributes_ybt4542_2016.state
     *
     * @mbg.generated Fri Feb 15 10:54:03 CST 2019
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wire_attributes_ybt4542_2016
     *
     * @mbg.generated Fri Feb 15 10:54:03 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", structure=").append(structure);
        sb.append(", state=").append(state);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}