package com.hbsi.domain;

import java.io.Serializable;

public class ZincLayerWeight implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zinc_layer_weight.id
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zinc_layer_weight.standard_num
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    private String standardNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zinc_layer_weight.surface_state
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    private String surfaceState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zinc_layer_weight.diamete_min
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    private Double diameteMin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zinc_layer_weight.diamete_max
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    private Double diameteMax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zinc_layer_weight.value
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    private Integer value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zinc_layer_weight.state
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zinc_layer_weight
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zinc_layer_weight.id
     *
     * @return the value of zinc_layer_weight.id
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zinc_layer_weight.id
     *
     * @param id the value for zinc_layer_weight.id
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zinc_layer_weight.standard_num
     *
     * @return the value of zinc_layer_weight.standard_num
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public String getStandardNum() {
        return standardNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zinc_layer_weight.standard_num
     *
     * @param standardNum the value for zinc_layer_weight.standard_num
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public void setStandardNum(String standardNum) {
        this.standardNum = standardNum == null ? null : standardNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zinc_layer_weight.surface_state
     *
     * @return the value of zinc_layer_weight.surface_state
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public String getSurfaceState() {
        return surfaceState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zinc_layer_weight.surface_state
     *
     * @param surfaceState the value for zinc_layer_weight.surface_state
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public void setSurfaceState(String surfaceState) {
        this.surfaceState = surfaceState == null ? null : surfaceState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zinc_layer_weight.diamete_min
     *
     * @return the value of zinc_layer_weight.diamete_min
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public Double getDiameteMin() {
        return diameteMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zinc_layer_weight.diamete_min
     *
     * @param diameteMin the value for zinc_layer_weight.diamete_min
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public void setDiameteMin(Double diameteMin) {
        this.diameteMin = diameteMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zinc_layer_weight.diamete_max
     *
     * @return the value of zinc_layer_weight.diamete_max
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public Double getDiameteMax() {
        return diameteMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zinc_layer_weight.diamete_max
     *
     * @param diameteMax the value for zinc_layer_weight.diamete_max
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public void setDiameteMax(Double diameteMax) {
        this.diameteMax = diameteMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zinc_layer_weight.value
     *
     * @return the value of zinc_layer_weight.value
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public Integer getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zinc_layer_weight.value
     *
     * @param value the value for zinc_layer_weight.value
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public void setValue(Integer value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zinc_layer_weight.state
     *
     * @return the value of zinc_layer_weight.state
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zinc_layer_weight.state
     *
     * @param state the value for zinc_layer_weight.state
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zinc_layer_weight
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", standardNum=").append(standardNum);
        sb.append(", surfaceState=").append(surfaceState);
        sb.append(", diameteMin=").append(diameteMin);
        sb.append(", diameteMax=").append(diameteMax);
        sb.append(", value=").append(value);
        sb.append(", state=").append(state);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}