package com.hbsi.domain;

import java.io.Serializable;

public class User implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.username
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_rank
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    private String userRank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_class
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    private String userClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.state
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.username
     *
     * @return the value of user.username
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.username
     *
     * @param username the value for user.username
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_rank
     *
     * @return the value of user.user_rank
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public String getUserRank() {
        return userRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_rank
     *
     * @param userRank the value for user.user_rank
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public void setUserRank(String userRank) {
        this.userRank = userRank == null ? null : userRank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_class
     *
     * @return the value of user.user_class
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public String getUserClass() {
        return userClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_class
     *
     * @param userClass the value for user.user_class
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public void setUserClass(String userClass) {
        this.userClass = userClass == null ? null : userClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.state
     *
     * @return the value of user.state
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.state
     *
     * @param state the value for user.state
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", username=").append(username);
        sb.append(", password=").append(password);
        sb.append(", userRank=").append(userRank);
        sb.append(", userClass=").append(userClass);
        sb.append(", state=").append(state);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}