package com.hbsi.dao;

import com.hbsi.domain.SampleRecordHistory;

public interface SampleRecordHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_record_history
     *
     * @mbg.generated Mon Mar 11 15:05:40 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_record_history
     *
     * @mbg.generated Mon Mar 11 15:05:40 CST 2019
     */
    int insert(SampleRecordHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_record_history
     *
     * @mbg.generated Mon Mar 11 15:05:40 CST 2019
     */
    int insertSelective(SampleRecordHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_record_history
     *
     * @mbg.generated Mon Mar 11 15:05:40 CST 2019
     */
    SampleRecordHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_record_history
     *
     * @mbg.generated Mon Mar 11 15:05:40 CST 2019
     */
    int updateByPrimaryKeySelective(SampleRecordHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_record_history
     *
     * @mbg.generated Mon Mar 11 15:05:40 CST 2019
     */
    int updateByPrimaryKey(SampleRecordHistory record);
}