package com.hbsi.domain;

import java.io.Serializable;
import java.sql.Timestamp;
import java.util.Date;

import com.hbsi.util.DateUtil;

public class SampleRecord implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_record.id
     *
     * @mbg.generated Fri Sep 28 10:58:34 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_record.entrustment_number
     *
     * @mbg.generated Fri Sep 28 10:58:34 CST 2018
     */
    private String entrustmentNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_record.sample_batch
     *
     * @mbg.generated Fri Sep 28 10:58:34 CST 2018
     */
    private Integer sampleBatch;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_record.sample_batch
     *
     * @mbg.generated Fri Sep 28 10:58:34 CST 2018
     */
    private Integer sampleNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_record.experimental_data
     *
     * @mbg.generated Fri Sep 28 10:58:34 CST 2018
     */
    private Double experimentalData;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_record.test_members_number
     *
     * @mbg.generated Fri Sep 28 10:58:34 CST 2018
     */
    private String testMembersNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_record.type
     *
     * @mbg.generated Fri Sep 28 10:58:34 CST 2018
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_record.machine_type
     *
     * @mbg.generated Fri Sep 28 10:58:34 CST 2018
     */
    private String machineType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_record.machine_number
     *
     * @mbg.generated Fri Sep 28 10:58:34 CST 2018
     */
    private String machineNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_record.create_date
     *
     * @mbg.generated Fri Sep 28 10:58:34 CST 2018
     */
    private Timestamp createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_record.state
     *
     * @mbg.generated Fri Sep 28 10:58:34 CST 2018
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sample_record
     *
     * @mbg.generated Fri Sep 28 10:58:34 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_record.id
     *
     * @return the value of sample_record.id
     *
     * @mbg.generated Fri Sep 28 10:58:34 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_record.id
     *
     * @param id the value for sample_record.id
     *
     * @mbg.generated Fri Sep 28 10:58:34 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_record.entrustment_number
     *
     * @return the value of sample_record.entrustment_number
     *
     * @mbg.generated Fri Sep 28 10:58:34 CST 2018
     */
    public String getEntrustmentNumber() {
        return entrustmentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_record.entrustment_number
     *
     * @param entrustmentNumber the value for sample_record.entrustment_number
     *
     * @mbg.generated Fri Sep 28 10:58:34 CST 2018
     */
    public void setEntrustmentNumber(String entrustmentNumber) {
        this.entrustmentNumber = entrustmentNumber == null ? null : entrustmentNumber.trim();
    }


    public Integer getSampleBatch() {
		return sampleBatch;
	}

	public void setSampleBatch(Integer sampleBatch) {
		this.sampleBatch = sampleBatch;
	}

	public Integer getSampleNumber() {
		return sampleNumber;
	}

	public void setSampleNumber(Integer sampleNumber) {
		this.sampleNumber = sampleNumber;
	}

	public Double getExperimentalData() {
		return experimentalData;
	}

	public void setExperimentalData(Double experimentalData) {
		this.experimentalData = experimentalData;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_record.test_members_number
     *
     * @return the value of sample_record.test_members_number
     *
     * @mbg.generated Fri Sep 28 10:58:34 CST 2018
     */
    public String getTestMembersNumber() {
        return testMembersNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_record.test_members_number
     *
     * @param testMembersNumber the value for sample_record.test_members_number
     *
     * @mbg.generated Fri Sep 28 10:58:34 CST 2018
     */
    public void setTestMembersNumber(String testMembersNumber) {
        this.testMembersNumber = testMembersNumber == null ? null : testMembersNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_record.type
     *
     * @return the value of sample_record.type
     *
     * @mbg.generated Fri Sep 28 10:58:34 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_record.type
     *
     * @param type the value for sample_record.type
     *
     * @mbg.generated Fri Sep 28 10:58:34 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_record.machine_type
     *
     * @return the value of sample_record.machine_type
     *
     * @mbg.generated Fri Sep 28 10:58:34 CST 2018
     */
    public String getMachineType() {
        return machineType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_record.machine_type
     *
     * @param machineType the value for sample_record.machine_type
     *
     * @mbg.generated Fri Sep 28 10:58:34 CST 2018
     */
    public void setMachineType(String machineType) {
        this.machineType = machineType == null ? null : machineType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_record.machine_number
     *
     * @return the value of sample_record.machine_number
     *
     * @mbg.generated Fri Sep 28 10:58:34 CST 2018
     */
    public String getMachineNumber() {
        return machineNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_record.machine_number
     *
     * @param machineNumber the value for sample_record.machine_number
     *
     * @mbg.generated Fri Sep 28 10:58:34 CST 2018
     */
    public void setMachineNumber(String machineNumber) {
        this.machineNumber = machineNumber == null ? null : machineNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_record.create_date
     *
     * @return the value of sample_record.create_date
     *
     * @mbg.generated Fri Sep 28 10:58:34 CST 2018
     */
    public String getCreateDate() {
        return DateUtil.formatDateTime(createDate);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_record.create_date
     *
     * @param createDate the value for sample_record.create_date
     *
     * @mbg.generated Fri Sep 28 10:58:34 CST 2018
     */
    public void setCreateDate(Timestamp createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_record.state
     *
     * @return the value of sample_record.state
     *
     * @mbg.generated Fri Sep 28 10:58:34 CST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_record.state
     *
     * @param state the value for sample_record.state
     *
     * @mbg.generated Fri Sep 28 10:58:34 CST 2018
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_record
     *
     * @mbg.generated Fri Sep 28 10:58:34 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", entrustmentNumber=").append(entrustmentNumber);
        sb.append(", sampleBatch=").append(sampleBatch);
        sb.append(", experimentalData=").append(experimentalData);
        sb.append(", testMembersNumber=").append(testMembersNumber);
        sb.append(", type=").append(type);
        sb.append(", machineType=").append(machineType);
        sb.append(", machineNumber=").append(machineNumber);
        sb.append(", createDate=").append(createDate);
        sb.append(", state=").append(state);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}