package com.hbsi.domain;

import java.io.Serializable;
import java.sql.Timestamp;
import java.util.Date;

public class EntrustmentHistory implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrustment_history.id
     *
     * @mbg.generated Thu Dec 06 09:00:46 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrustment_history.sample_batch
     *
     * @mbg.generated Thu Dec 06 09:00:46 CST 2018
     */
    private Integer sampleBatch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrustment_history.entrustment_number
     *
     * @mbg.generated Thu Dec 06 09:00:46 CST 2018
     */
    private String entrustmentNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrustment_history.state
     *
     * @mbg.generated Thu Dec 06 09:00:46 CST 2018
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrustment_history.create_time
     *
     * @mbg.generated Thu Dec 06 09:00:46 CST 2018
     */
    private Timestamp createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table entrustment_history
     *
     * @mbg.generated Thu Dec 06 09:00:46 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrustment_history.id
     *
     * @return the value of entrustment_history.id
     *
     * @mbg.generated Thu Dec 06 09:00:46 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrustment_history.id
     *
     * @param id the value for entrustment_history.id
     *
     * @mbg.generated Thu Dec 06 09:00:46 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrustment_history.sample_batch
     *
     * @return the value of entrustment_history.sample_batch
     *
     * @mbg.generated Thu Dec 06 09:00:46 CST 2018
     */
    public Integer getSampleBatch() {
        return sampleBatch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrustment_history.sample_batch
     *
     * @param sampleBatch the value for entrustment_history.sample_batch
     *
     * @mbg.generated Thu Dec 06 09:00:46 CST 2018
     */
    public void setSampleBatch(Integer sampleBatch) {
        this.sampleBatch = sampleBatch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrustment_history.entrustment_number
     *
     * @return the value of entrustment_history.entrustment_number
     *
     * @mbg.generated Thu Dec 06 09:00:46 CST 2018
     */
    public String getEntrustmentNumber() {
        return entrustmentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrustment_history.entrustment_number
     *
     * @param entrustmentNumber the value for entrustment_history.entrustment_number
     *
     * @mbg.generated Thu Dec 06 09:00:46 CST 2018
     */
    public void setEntrustmentNumber(String entrustmentNumber) {
        this.entrustmentNumber = entrustmentNumber == null ? null : entrustmentNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrustment_history.state
     *
     * @return the value of entrustment_history.state
     *
     * @mbg.generated Thu Dec 06 09:00:46 CST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrustment_history.state
     *
     * @param state the value for entrustment_history.state
     *
     * @mbg.generated Thu Dec 06 09:00:46 CST 2018
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    

    public Timestamp getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Timestamp createTime) {
		this.createTime = createTime;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrustment_history
     *
     * @mbg.generated Thu Dec 06 09:00:46 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", sampleBatch=").append(sampleBatch);
        sb.append(", entrustmentNumber=").append(entrustmentNumber);
        sb.append(", state=").append(state);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}