package com.hbsi.domain;

import java.io.Serializable;

public class DiameterDeviation implements Serializable {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column diameter_deviation.id
	 *
	 * @mbg.generated Wed Sep 26 15:54:22 CST 2018
	 */
	private Integer id;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column diameter_deviation.standard_num
	 *
	 * @mbg.generated Wed Sep 26 15:54:22 CST 2018
	 */
	private String standardNum;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column diameter_deviation.diamete_min
	 *
	 * @mbg.generated Wed Sep 26 15:54:22 CST 2018
	 */
	private Double diameteMin;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column diameter_deviation.diamete_max
	 *
	 * @mbg.generated Wed Sep 26 15:54:22 CST 2018
	 */
	private Double diameteMax;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column diameter_deviation.type
	 *
	 * @mbg.generated Wed Sep 26 15:54:22 CST 2018
	 */
	private String type;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column diameter_deviation.value
	 *
	 * @mbg.generated Wed Sep 26 15:54:22 CST 2018
	 */
	private Double value;
	/**
	 * 用于en12385标准哦
	 */
	private String usage;
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column diameter_deviation.state
	 *
	 * @mbg.generated Wed Sep 26 15:54:22 CST 2018
	 */
	private String state;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table diameter_deviation
	 *
	 * @mbg.generated Wed Sep 26 15:54:22 CST 2018
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column diameter_deviation.id
	 *
	 * @return the value of diameter_deviation.id
	 *
	 * @mbg.generated Wed Sep 26 15:54:22 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column diameter_deviation.id
	 *
	 * @param id the value for diameter_deviation.id
	 *
	 * @mbg.generated Wed Sep 26 15:54:22 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column diameter_deviation.standard_num
	 *
	 * @return the value of diameter_deviation.standard_num
	 *
	 * @mbg.generated Wed Sep 26 15:54:22 CST 2018
	 */
	public String getStandardNum() {
		return standardNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column diameter_deviation.standard_num
	 *
	 * @param standardNum the value for diameter_deviation.standard_num
	 *
	 * @mbg.generated Wed Sep 26 15:54:22 CST 2018
	 */
	public void setStandardNum(String standardNum) {
		this.standardNum = standardNum == null ? null : standardNum.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column diameter_deviation.diamete_min
	 *
	 * @return the value of diameter_deviation.diamete_min
	 *
	 * @mbg.generated Wed Sep 26 15:54:22 CST 2018
	 */
	public Double getDiameteMin() {
		return diameteMin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column diameter_deviation.diamete_min
	 *
	 * @param diameteMin the value for diameter_deviation.diamete_min
	 *
	 * @mbg.generated Wed Sep 26 15:54:22 CST 2018
	 */
	public void setDiameteMin(Double diameteMin) {
		this.diameteMin = diameteMin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column diameter_deviation.diamete_max
	 *
	 * @return the value of diameter_deviation.diamete_max
	 *
	 * @mbg.generated Wed Sep 26 15:54:22 CST 2018
	 */
	public Double getDiameteMax() {
		return diameteMax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column diameter_deviation.diamete_max
	 *
	 * @param diameteMax the value for diameter_deviation.diamete_max
	 *
	 * @mbg.generated Wed Sep 26 15:54:22 CST 2018
	 */
	public void setDiameteMax(Double diameteMax) {
		this.diameteMax = diameteMax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column diameter_deviation.type
	 *
	 * @return the value of diameter_deviation.type
	 *
	 * @mbg.generated Wed Sep 26 15:54:22 CST 2018
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column diameter_deviation.type
	 *
	 * @param type the value for diameter_deviation.type
	 *
	 * @mbg.generated Wed Sep 26 15:54:22 CST 2018
	 */
	public void setType(String type) {
		this.type = type == null ? null : type.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column diameter_deviation.value
	 *
	 * @return the value of diameter_deviation.value
	 *
	 * @mbg.generated Wed Sep 26 15:54:22 CST 2018
	 */
	public Double getValue() {
		return value;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column diameter_deviation.value
	 *
	 * @param value the value for diameter_deviation.value
	 *
	 * @mbg.generated Wed Sep 26 15:54:22 CST 2018
	 */
	public void setValue(Double value) {
		this.value = value;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column diameter_deviation.state
	 *
	 * @return the value of diameter_deviation.state
	 *
	 * @mbg.generated Wed Sep 26 15:54:22 CST 2018
	 */
	public String getState() {
		return state;
	}

	public String getUsage() {
		return usage;
	}

	public void setUsage(String usage) {
		this.usage = usage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column diameter_deviation.state
	 *
	 * @param state the value for diameter_deviation.state
	 *
	 * @mbg.generated Wed Sep 26 15:54:22 CST 2018
	 */
	public void setState(String state) {
		this.state = state == null ? null : state.trim();
	}

	@Override
	public String toString() {
		return "DiameterDeviation [id=" + id + ", standardNum=" + standardNum + ", diameteMin=" + diameteMin
				+ ", diameteMax=" + diameteMax + ", type=" + type + ", value=" + value + ", usage=" + usage + ", state="
				+ state + "]";
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table diameter_deviation
	 *
	 * @mbg.generated Wed Sep 26 15:54:22 CST 2018
	 */
	
}