package com.hbsi.dao;

import java.util.List;

import com.hbsi.domain.WireAttributesYbt45422016;

public interface WireAttributesYbt45422016Mapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table wire_attributes_ybt4542_2016
	 *
	 * @mbg.generated Fri Feb 15 10:54:03 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table wire_attributes_ybt4542_2016
	 *
	 * @mbg.generated Fri Feb 15 10:54:03 CST 2019
	 */
	int insert(WireAttributesYbt45422016 record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table wire_attributes_ybt4542_2016
	 *
	 * @mbg.generated Fri Feb 15 10:54:03 CST 2019
	 */
	int insertSelective(WireAttributesYbt45422016 record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table wire_attributes_ybt4542_2016
	 *
	 * @mbg.generated Fri Feb 15 10:54:03 CST 2019
	 */
	WireAttributesYbt45422016 selectByPrimaryKey(Integer id);
    /**
     * 查找所有的结构
     * @return
     */
	List<WireAttributesYbt45422016> selectAllStruc();
	/**
	 * 根据模糊的结构名查询对应的WireAttributesYbt45422016列表
	 * @return
	 */
	List<WireAttributesYbt45422016> selectByBlurStruc(String blurStruc);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table wire_attributes_ybt4542_2016
	 *
	 * @mbg.generated Fri Feb 15 10:54:03 CST 2019
	 */
	int updateByPrimaryKeySelective(WireAttributesYbt45422016 record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table wire_attributes_ybt4542_2016
	 *
	 * @mbg.generated Fri Feb 15 10:54:03 CST 2019
	 */
	int updateByPrimaryKey(WireAttributesYbt45422016 record);
}