package com.hbsi.dao;

import com.hbsi.domain.StrengthDeviation;
import com.hbsi.entity.WireRopeData;

public interface StrengthDeviationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table strength_deviation
     *
     * @mbg.generated Wed Oct 31 11:06:55 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table strength_deviation
     *
     * @mbg.generated Wed Oct 31 11:06:55 CST 2018
     */
    int insert(StrengthDeviation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table strength_deviation
     *
     * @mbg.generated Wed Oct 31 11:06:55 CST 2018
     */
    int insertSelective(StrengthDeviation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table strength_deviation
     *
     * @mbg.generated Wed Oct 31 11:06:55 CST 2018
     */
    StrengthDeviation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table strength_deviation
     *
     * @mbg.generated Wed Oct 31 11:06:55 CST 2018
     */
    int updateByPrimaryKeySelective(StrengthDeviation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table strength_deviation
     *
     * @mbg.generated Wed Oct 31 11:06:55 CST 2018
     */
    int updateByPrimaryKey(StrengthDeviation record);
    /**
     * 根据标准和公称直径查询强度值
     * @param data
     * @return
     */
    StrengthDeviation selectByDiamate(WireRopeData data);
}