package com.hbsi.dao;

import java.util.List;

import com.hbsi.domain.WireAttributesApi9a2011;

public interface WireAttributesApi9a2011Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wire_attributes_api_9a_2011
     *
     * @mbg.generated Thu Feb 21 16:49:36 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wire_attributes_api_9a_2011
     *
     * @mbg.generated Thu Feb 21 16:49:36 CST 2019
     */
    int insert(WireAttributesApi9a2011 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wire_attributes_api_9a_2011
     *
     * @mbg.generated Thu Feb 21 16:49:36 CST 2019
     */
    int insertSelective(WireAttributesApi9a2011 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wire_attributes_api_9a_2011
     *
     * @mbg.generated Thu Feb 21 16:49:36 CST 2019
     */
    WireAttributesApi9a2011 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wire_attributes_api_9a_2011
     *
     * @mbg.generated Thu Feb 21 16:49:36 CST 2019
     */
    int updateByPrimaryKeySelective(WireAttributesApi9a2011 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wire_attributes_api_9a_2011
     *
     * @mbg.generated Thu Feb 21 16:49:36 CST 2019
     */
    int updateByPrimaryKey(WireAttributesApi9a2011 record);
    
    WireAttributesApi9a2011 selectByFilling(String structure);
    /**
     * 
     * 模糊查询所有结构
     * @return
     */
    List<WireAttributesApi9a2011> selectByBlurStruc(String blurStruc);
   /** 
    * 查询所有结构
    * @param blurStruc
    * @return
    */
    List<WireAttributesApi9a2011> selectAllStruc();
}