package com.hbsi.dao;

import java.util.List;

import com.hbsi.domain.DiameterDeviation;
import com.hbsi.entity.WireRopeData;

public interface DiameterDeviationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diameter_deviation
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    int deleteByPrimaryKey(Integer id);
    /**
     * 删除直径表所有信息
     * @return
     */
    int deleteAllData();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diameter_deviation
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    int insert(DiameterDeviation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diameter_deviation
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    int insertSelective(DiameterDeviation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diameter_deviation
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    DiameterDeviation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diameter_deviation
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    int updateByPrimaryKeySelective(DiameterDeviation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diameter_deviation
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    int updateByPrimaryKey(DiameterDeviation record);
    /**
     * 根据公称直径、表面状态、标准号查询直径允许偏差
     * @param data
     * @return
     */
    DiameterDeviation selectDiaByType(WireRopeData data);
    /**
     *  跟楼上的区别在于表面状态的数据类型：只有两种A或者U,B,AB
     * @param data
     * @return
     */
    DiameterDeviation selectDiaByBlurType(WireRopeData data);
    /**
     * 查找得到直径表所有信息
     * @param data
     * @return
     */
    List<DiameterDeviation> selectDiameterDeviation();
}