package com.hbsi.dao;

import java.util.List;

import com.hbsi.domain.WireAttributesGBT89182006;

public interface WireAttributesGBT89182006Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wire_attributes_gbt8918_2006
     *
     * @mbg.generated Wed Oct 31 11:15:14 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wire_attributes_gbt8918_2006
     *
     * @mbg.generated Wed Oct 31 11:15:14 CST 2018
     */
    int insert(WireAttributesGBT89182006 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wire_attributes_gbt8918_2006
     *
     * @mbg.generated Wed Oct 31 11:15:14 CST 2018
     */
    int insertSelective(WireAttributesGBT89182006 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wire_attributes_gbt8918_2006
     *
     * @mbg.generated Wed Oct 31 11:15:14 CST 2018
     */
    WireAttributesGBT89182006 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wire_attributes_gbt8918_2006
     *
     * @mbg.generated Wed Oct 31 11:15:14 CST 2018
     */
    int updateByPrimaryKeySelective(WireAttributesGBT89182006 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wire_attributes_gbt8918_2006
     *
     * @mbg.generated Wed Oct 31 11:15:14 CST 2018
     */
    int updateByPrimaryKey(WireAttributesGBT89182006 record);
    
    /**
     * 查询所有结构
     * @return
     */
    List<WireAttributesGBT89182006> selectWireAttributesGBT89182006Structure();
    /**
     * 根据钢丝绳结构查询系数
     * @param structure
     * @return
     */
    WireAttributesGBT89182006 selectByStructure(String structure);
    /**
     * 查询所有表数据
     * @return
     */
	List<WireAttributesGBT89182006> selectWireAttr();
	/**
	 * 通过模糊的结构名查询WireAttributesGBT89182006列表
	 * @param blurStruc
	 * @return
	 */
	List<WireAttributesGBT89182006> selectByBlurStruc(String blurStruc);
    /**
     * 删除所有数据啊
     */
	void deleteAllData();
}