package com.hbsi.domain;

import java.io.Serializable;
import java.util.Date;

public class SampleRecordHistory implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_record_history.id
     *
     * @mbg.generated Mon Mar 11 15:05:40 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_record_history.entrustment_number
     *
     * @mbg.generated Mon Mar 11 15:05:40 CST 2019
     */
    private String entrustmentNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_record_history.sample_batch
     *
     * @mbg.generated Mon Mar 11 15:05:40 CST 2019
     */
    private Integer sampleBatch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_record_history.sample_number
     *
     * @mbg.generated Mon Mar 11 15:05:40 CST 2019
     */
    private Integer sampleNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_record_history.experimental_data
     *
     * @mbg.generated Mon Mar 11 15:05:40 CST 2019
     */
    private Double experimentalData;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_record_history.test_members_number
     *
     * @mbg.generated Mon Mar 11 15:05:40 CST 2019
     */
    private String testMembersNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_record_history.type
     *
     * @mbg.generated Mon Mar 11 15:05:40 CST 2019
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_record_history.machine_type
     *
     * @mbg.generated Mon Mar 11 15:05:40 CST 2019
     */
    private String machineType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_record_history.machine_number
     *
     * @mbg.generated Mon Mar 11 15:05:40 CST 2019
     */
    private String machineNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_record_history.create_date
     *
     * @mbg.generated Mon Mar 11 15:05:40 CST 2019
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_record_history.state
     *
     * @mbg.generated Mon Mar 11 15:05:40 CST 2019
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sample_record_history
     *
     * @mbg.generated Mon Mar 11 15:05:40 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_record_history.id
     *
     * @return the value of sample_record_history.id
     *
     * @mbg.generated Mon Mar 11 15:05:40 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_record_history.id
     *
     * @param id the value for sample_record_history.id
     *
     * @mbg.generated Mon Mar 11 15:05:40 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_record_history.entrustment_number
     *
     * @return the value of sample_record_history.entrustment_number
     *
     * @mbg.generated Mon Mar 11 15:05:40 CST 2019
     */
    public String getEntrustmentNumber() {
        return entrustmentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_record_history.entrustment_number
     *
     * @param entrustmentNumber the value for sample_record_history.entrustment_number
     *
     * @mbg.generated Mon Mar 11 15:05:40 CST 2019
     */
    public void setEntrustmentNumber(String entrustmentNumber) {
        this.entrustmentNumber = entrustmentNumber == null ? null : entrustmentNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_record_history.sample_batch
     *
     * @return the value of sample_record_history.sample_batch
     *
     * @mbg.generated Mon Mar 11 15:05:40 CST 2019
     */
    public Integer getSampleBatch() {
        return sampleBatch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_record_history.sample_batch
     *
     * @param sampleBatch the value for sample_record_history.sample_batch
     *
     * @mbg.generated Mon Mar 11 15:05:40 CST 2019
     */
    public void setSampleBatch(Integer sampleBatch) {
        this.sampleBatch = sampleBatch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_record_history.sample_number
     *
     * @return the value of sample_record_history.sample_number
     *
     * @mbg.generated Mon Mar 11 15:05:40 CST 2019
     */
    public Integer getSampleNumber() {
        return sampleNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_record_history.sample_number
     *
     * @param sampleNumber the value for sample_record_history.sample_number
     *
     * @mbg.generated Mon Mar 11 15:05:40 CST 2019
     */
    public void setSampleNumber(Integer sampleNumber) {
        this.sampleNumber = sampleNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_record_history.experimental_data
     *
     * @return the value of sample_record_history.experimental_data
     *
     * @mbg.generated Mon Mar 11 15:05:40 CST 2019
     */
    public Double getExperimentalData() {
        return experimentalData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_record_history.experimental_data
     *
     * @param experimentalData the value for sample_record_history.experimental_data
     *
     * @mbg.generated Mon Mar 11 15:05:40 CST 2019
     */
    public void setExperimentalData(Double experimentalData) {
        this.experimentalData = experimentalData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_record_history.test_members_number
     *
     * @return the value of sample_record_history.test_members_number
     *
     * @mbg.generated Mon Mar 11 15:05:40 CST 2019
     */
    public String getTestMembersNumber() {
        return testMembersNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_record_history.test_members_number
     *
     * @param testMembersNumber the value for sample_record_history.test_members_number
     *
     * @mbg.generated Mon Mar 11 15:05:40 CST 2019
     */
    public void setTestMembersNumber(String testMembersNumber) {
        this.testMembersNumber = testMembersNumber == null ? null : testMembersNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_record_history.type
     *
     * @return the value of sample_record_history.type
     *
     * @mbg.generated Mon Mar 11 15:05:40 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_record_history.type
     *
     * @param type the value for sample_record_history.type
     *
     * @mbg.generated Mon Mar 11 15:05:40 CST 2019
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_record_history.machine_type
     *
     * @return the value of sample_record_history.machine_type
     *
     * @mbg.generated Mon Mar 11 15:05:40 CST 2019
     */
    public String getMachineType() {
        return machineType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_record_history.machine_type
     *
     * @param machineType the value for sample_record_history.machine_type
     *
     * @mbg.generated Mon Mar 11 15:05:40 CST 2019
     */
    public void setMachineType(String machineType) {
        this.machineType = machineType == null ? null : machineType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_record_history.machine_number
     *
     * @return the value of sample_record_history.machine_number
     *
     * @mbg.generated Mon Mar 11 15:05:40 CST 2019
     */
    public String getMachineNumber() {
        return machineNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_record_history.machine_number
     *
     * @param machineNumber the value for sample_record_history.machine_number
     *
     * @mbg.generated Mon Mar 11 15:05:40 CST 2019
     */
    public void setMachineNumber(String machineNumber) {
        this.machineNumber = machineNumber == null ? null : machineNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_record_history.create_date
     *
     * @return the value of sample_record_history.create_date
     *
     * @mbg.generated Mon Mar 11 15:05:40 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_record_history.create_date
     *
     * @param createDate the value for sample_record_history.create_date
     *
     * @mbg.generated Mon Mar 11 15:05:40 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_record_history.state
     *
     * @return the value of sample_record_history.state
     *
     * @mbg.generated Mon Mar 11 15:05:40 CST 2019
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_record_history.state
     *
     * @param state the value for sample_record_history.state
     *
     * @mbg.generated Mon Mar 11 15:05:40 CST 2019
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_record_history
     *
     * @mbg.generated Mon Mar 11 15:05:40 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", entrustmentNumber=").append(entrustmentNumber);
        sb.append(", sampleBatch=").append(sampleBatch);
        sb.append(", sampleNumber=").append(sampleNumber);
        sb.append(", experimentalData=").append(experimentalData);
        sb.append(", testMembersNumber=").append(testMembersNumber);
        sb.append(", type=").append(type);
        sb.append(", machineType=").append(machineType);
        sb.append(", machineNumber=").append(machineNumber);
        sb.append(", createDate=").append(createDate);
        sb.append(", state=").append(state);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}