package com.hbsi.domain;

import java.io.Serializable;

public class SteelTensileStrength implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column steel_tensile_strength.id
     *
     * @mbg.generated Wed Oct 10 10:40:49 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column steel_tensile_strength.standard _num
     *
     * @mbg.generated Wed Oct 10 10:40:49 CST 2018
     */
    private String standardNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column steel_tensile_strength.rated_strength
     *
     * @mbg.generated Wed Oct 10 10:40:49 CST 2018
     */
    private String ratedStrength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column steel_tensile_strength.usage
     *
     * @mbg.generated Wed Oct 10 10:40:49 CST 2018
     */
    private String usage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column steel_tensile_strength.diamete_min
     *
     * @mbg.generated Wed Oct 10 10:40:49 CST 2018
     */
    private Double diameteMin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column steel_tensile_strength.diamete_max
     *
     * @mbg.generated Wed Oct 10 10:40:49 CST 2018
     */
    private Double diameteMax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column steel_tensile_strength.strength_value_min
     *
     * @mbg.generated Wed Oct 10 10:40:49 CST 2018
     */
    private Integer strengthValueMin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column steel_tensile_strength.strength_value_max
     *
     * @mbg.generated Wed Oct 10 10:40:49 CST 2018
     */
    private Integer strengthValueMax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column steel_tensile_strength.state
     *
     * @mbg.generated Wed Oct 10 10:40:49 CST 2018
     */
    private String state;
    private Double fDiamete;
    private Integer strengthValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table steel_tensile_strength
     *
     * @mbg.generated Wed Oct 10 10:40:49 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column steel_tensile_strength.id
     *
     * @return the value of steel_tensile_strength.id
     *
     * @mbg.generated Wed Oct 10 10:40:49 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column steel_tensile_strength.id
     *
     * @param id the value for steel_tensile_strength.id
     *
     * @mbg.generated Wed Oct 10 10:40:49 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column steel_tensile_strength.standard _num
     *
     * @return the value of steel_tensile_strength.standard _num
     *
     * @mbg.generated Wed Oct 10 10:40:49 CST 2018
     */
    public String getStandardNum() {
        return standardNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column steel_tensile_strength.standard _num
     *
     * @param standardNum the value for steel_tensile_strength.standard _num
     *
     * @mbg.generated Wed Oct 10 10:40:49 CST 2018
     */
    public void setStandardNum(String standardNum) {
        this.standardNum = standardNum == null ? null : standardNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column steel_tensile_strength.rated_strength
     *
     * @return the value of steel_tensile_strength.rated_strength
     *
     * @mbg.generated Wed Oct 10 10:40:49 CST 2018
     */
    public String getRatedStrength() {
        return ratedStrength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column steel_tensile_strength.rated_strength
     *
     * @param ratedStrength the value for steel_tensile_strength.rated_strength
     *
     * @mbg.generated Wed Oct 10 10:40:49 CST 2018
     */
    public void setRatedStrength(String ratedStrength) {
        this.ratedStrength = ratedStrength == null ? null : ratedStrength.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column steel_tensile_strength.usage
     *
     * @return the value of steel_tensile_strength.usage
     *
     * @mbg.generated Wed Oct 10 10:40:49 CST 2018
     */
    public String getUsage() {
        return usage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column steel_tensile_strength.usage
     *
     * @param usage the value for steel_tensile_strength.usage
     *
     * @mbg.generated Wed Oct 10 10:40:49 CST 2018
     */
    public void setUsage(String usage) {
        this.usage = usage == null ? null : usage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column steel_tensile_strength.diamete_min
     *
     * @return the value of steel_tensile_strength.diamete_min
     *
     * @mbg.generated Wed Oct 10 10:40:49 CST 2018
     */
    public Double getDiameteMin() {
        return diameteMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column steel_tensile_strength.diamete_min
     *
     * @param diameteMin the value for steel_tensile_strength.diamete_min
     *
     * @mbg.generated Wed Oct 10 10:40:49 CST 2018
     */
    public void setDiameteMin(Double diameteMin) {
        this.diameteMin = diameteMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column steel_tensile_strength.diamete_max
     *
     * @return the value of steel_tensile_strength.diamete_max
     *
     * @mbg.generated Wed Oct 10 10:40:49 CST 2018
     */
    public Double getDiameteMax() {
        return diameteMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column steel_tensile_strength.diamete_max
     *
     * @param diameteMax the value for steel_tensile_strength.diamete_max
     *
     * @mbg.generated Wed Oct 10 10:40:49 CST 2018
     */
    public void setDiameteMax(Double diameteMax) {
        this.diameteMax = diameteMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column steel_tensile_strength.strength_value_min
     *
     * @return the value of steel_tensile_strength.strength_value_min
     *
     * @mbg.generated Wed Oct 10 10:40:49 CST 2018
     */
    public Integer getStrengthValueMin() {
        return strengthValueMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column steel_tensile_strength.strength_value_min
     *
     * @param strengthValueMin the value for steel_tensile_strength.strength_value_min
     *
     * @mbg.generated Wed Oct 10 10:40:49 CST 2018
     */
    public void setStrengthValueMin(Integer strengthValueMin) {
        this.strengthValueMin = strengthValueMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column steel_tensile_strength.strength_value_max
     *
     * @return the value of steel_tensile_strength.strength_value_max
     *
     * @mbg.generated Wed Oct 10 10:40:49 CST 2018
     */
    public Integer getStrengthValueMax() {
        return strengthValueMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column steel_tensile_strength.strength_value_max
     *
     * @param strengthValueMax the value for steel_tensile_strength.strength_value_max
     *
     * @mbg.generated Wed Oct 10 10:40:49 CST 2018
     */
    public void setStrengthValueMax(Integer strengthValueMax) {
        this.strengthValueMax = strengthValueMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column steel_tensile_strength.state
     *
     * @return the value of steel_tensile_strength.state
     *
     * @mbg.generated Wed Oct 10 10:40:49 CST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column steel_tensile_strength.state
     *
     * @param state the value for steel_tensile_strength.state
     *
     * @mbg.generated Wed Oct 10 10:40:49 CST 2018
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }
    
    public Double getfDiamete() {
		return fDiamete;
	}

	public void setfDiamete(Double fDiamete) {
		this.fDiamete = fDiamete;
	}

	public Integer getStrengthValue() {
		return strengthValue;
	}

	public void setStrengthValue(Integer strengthValue) {
		this.strengthValue = strengthValue;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table steel_tensile_strength
     *
     * @mbg.generated Wed Oct 10 10:40:49 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", standardNum=").append(standardNum);
        sb.append(", ratedStrength=").append(ratedStrength);
        sb.append(", usage=").append(usage);
        sb.append(", diameteMin=").append(diameteMin);
        sb.append(", diameteMax=").append(diameteMax);
        sb.append(", strengthValueMin=").append(strengthValueMin);
        sb.append(", strengthValueMax=").append(strengthValueMax);
        sb.append(", state=").append(state);
        sb.append(", fDiamete=").append(fDiamete);
        sb.append(", strengthValue=").append(strengthValue);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}