package com.hbsi.dao;

import java.util.List;

import com.hbsi.domain.BreakConclusion;

public interface BreakConclusionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table break_conclusion
     *
     * @mbg.generated Thu Dec 06 17:20:36 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table break_conclusion
     *
     * @mbg.generated Thu Dec 06 17:20:36 CST 2018
     */
    int insert(BreakConclusion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table break_conclusion
     *
     * @mbg.generated Thu Dec 06 17:20:36 CST 2018
     */
    int insertSelective(BreakConclusion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table break_conclusion
     *
     * @mbg.generated Thu Dec 06 17:20:36 CST 2018
     */
    BreakConclusion selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table break_conclusion
     *
     * @mbg.generated Thu Dec 06 17:20:36 CST 2018
     */
    int updateByPrimaryKeySelective(BreakConclusion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table break_conclusion
     *
     * @mbg.generated Thu Dec 06 17:20:36 CST 2018
     */
    int updateByPrimaryKey(BreakConclusion record);
    /**
     * 根据委托单号删除数据
     * @param entrustNum
     * @return
     */
    int deleteByEntrustNum(String entrustNum);
    /**
     * 根据委托单号查询数据
     * @param entrustNum
     * @return
     */
    List<BreakConclusion> selectByEntrustNum(String entrustNum);
    /**
     * 根据委托单号和公称直径查询某条拆股实验结论数据
     * @param breakConclusion
     * @return
     */
    BreakConclusion selectByEntrustAndNdiameter(BreakConclusion breakConclusion);
    
}