package com.hbsi.dao;

import java.util.List;

import com.hbsi.domain.User;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    int updateByPrimaryKey(User record);
    /**
     * 根据用户名查询用户
     * @param username
     * @return
     */
    User selectByUsername(String username);
    /**
     * 删除用户
     * @param id
     * @return
     */
    int deleteUser(Integer id);
    /**
     * 重置用户密码
     * @param user
     * @return
     */
    int resetPassword(User user);
    /**
     * 查询用户列表
     * @return
     */
    List<User> selectAllUser();
}