package com.hbsi.dao;

import com.hbsi.domain.VersonNumber;

public interface VersonNumberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verson_number
     *
     * @mbg.generated Thu Dec 20 17:23:31 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verson_number
     *
     * @mbg.generated Thu Dec 20 17:23:31 CST 2018
     */
    int insert(VersonNumber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verson_number
     *
     * @mbg.generated Thu Dec 20 17:23:31 CST 2018
     */
    int insertSelective(VersonNumber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verson_number
     *
     * @mbg.generated Thu Dec 20 17:23:31 CST 2018
     */
    VersonNumber selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verson_number
     *
     * @mbg.generated Thu Dec 20 17:23:31 CST 2018
     */
    int updateByPrimaryKeySelective(VersonNumber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verson_number
     *
     * @mbg.generated Thu Dec 20 17:23:31 CST 2018
     */
    int updateByPrimaryKey(VersonNumber record);
    /**
     * 根据报告种类查询版本号
     * @param reportCategory
     * @return
     */
    VersonNumber selectByReportCategory(String reportCategory);
}