package com.hbsi.dao;

import java.util.List;

import com.hbsi.domain.WireAttributesGbt201182017;

public interface WireAttributesGbt201182017Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wire_attributes_gbt20118_2017
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    int deleteByPrimaryKey(Integer id);
    /**
     * s删除整张表的数据
     * @return
     */
    int deleteAllData();
    
    /**
     * 查询 wireattributesgbt201182017 所有结构
     * @return
     */
    List<WireAttributesGbt201182017> selectWireAttributesGbt201182017Structure();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wire_attributes_gbt20118_2017
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    int insert(WireAttributesGbt201182017 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wire_attributes_gbt20118_2017
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    int insertSelective(WireAttributesGbt201182017 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wire_attributes_gbt20118_2017
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    WireAttributesGbt201182017 selectByPrimaryKey(Integer id);
    /**
     * 得到整张表数据
     * @return
     */
    List<WireAttributesGbt201182017> selectWireAttributesGbt201182017();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wire_attributes_gbt20118_2017
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    int updateByPrimaryKeySelective(WireAttributesGbt201182017 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wire_attributes_gbt20118_2017
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    int updateByPrimaryKey(WireAttributesGbt201182017 record);
    //根据结构查询捻制损失系数
    WireAttributesGbt201182017 selectTanningByStructure(String structure);
    /**
     * 根据模糊的结构名查询WireAttributesGbt201182017列表
     * @param blurStruc
     * @return
     */
    List<WireAttributesGbt201182017> selectByBlurStruc(String blurStruc);
}