package com.hbsi.dao;

import java.util.List;

import com.hbsi.domain.WireStandard;

public interface WireStandardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wire_standard
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wire_standard
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    int insert(WireStandard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wire_standard
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    int insertSelective(WireStandard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wire_standard
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    WireStandard selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wire_standard
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    int updateByPrimaryKeySelective(WireStandard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wire_standard
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    int updateByPrimaryKey(WireStandard record);
    /**
     * 查询系统中所有的标准文件
     * @return
     */
    List<WireStandard> selectWireStandardList();
    /**
     * 根据委托号查询标准汉语名称
     */
    WireStandard selectWireStandByStandNum(String standNum);
}