package com.hbsi.dao;

import java.util.List;

import com.hbsi.domain.WireAttributesIso24082004;

public interface WireAttributesIso24082004Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wire_attributes_iso_2408_2004
     *
     * @mbg.generated Mon Feb 25 09:30:06 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wire_attributes_iso_2408_2004
     *
     * @mbg.generated Mon Feb 25 09:30:06 CST 2019
     */
    int insert(WireAttributesIso24082004 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wire_attributes_iso_2408_2004
     *
     * @mbg.generated Mon Feb 25 09:30:06 CST 2019
     */
    int insertSelective(WireAttributesIso24082004 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wire_attributes_iso_2408_2004
     *
     * @mbg.generated Mon Feb 25 09:30:06 CST 2019
     */
    WireAttributesIso24082004 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wire_attributes_iso_2408_2004
     *
     * @mbg.generated Mon Feb 25 09:30:06 CST 2019
     */
    int updateByPrimaryKeySelective(WireAttributesIso24082004 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wire_attributes_iso_2408_2004
     *
     * @mbg.generated Mon Feb 25 09:30:06 CST 2019
     */
    int updateByPrimaryKey(WireAttributesIso24082004 record);
    /**
     * 
     * 模糊查询所有结构
     * @return
     */
    List<WireAttributesIso24082004> selectByBlurStruc(String blurStruc);
   /** 
    * 查询所有结构
    * @param blurStruc
    * @return
    */
    List<WireAttributesIso24082004> selectAllStruc();
}