package com.hbsi.domain;

import java.io.Serializable;

public class WireAttributesYbt53592010 implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wire_attributes_ybt5359_2010.id
     *
     * @mbg.generated Tue Oct 30 14:14:52 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wire_attributes_ybt5359_2010.structure
     *
     * @mbg.generated Tue Oct 30 14:14:52 CST 2018
     */
    private String structure;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wire_attributes_ybt5359_2010.minimum_breaking_force
     *
     * @mbg.generated Tue Oct 30 14:14:52 CST 2018
     */
    private Double minimumBreakingForce;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wire_attributes_ybt5359_2010.tanning_loss_factor
     *
     * @mbg.generated Tue Oct 30 14:14:52 CST 2018
     */
    private Double tanningLossFactor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wire_attributes_ybt5359_2010.partial_intensity_low
     *
     * @mbg.generated Tue Oct 30 14:14:52 CST 2018
     */
    private Integer partialIntensityLow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wire_attributes_ybt5359_2010.partial_reverse_low
     *
     * @mbg.generated Tue Oct 30 14:14:52 CST 2018
     */
    private Integer partialReverseLow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wire_attributes_ybt5359_2010.intensity_low
     *
     * @mbg.generated Tue Oct 30 14:14:52 CST 2018
     */
    private Integer intensityLow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wire_attributes_ybt5359_2010.reverse_low
     *
     * @mbg.generated Tue Oct 30 14:14:52 CST 2018
     */
    private Integer reverseLow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wire_attributes_ybt5359_2010.twist_distance
     *
     * @mbg.generated Tue Oct 30 14:14:52 CST 2018
     */
    private Double twistDistance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wire_attributes_ybt5359_2010.state
     *
     * @mbg.generated Tue Oct 30 14:14:52 CST 2018
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wire_attributes_ybt5359_2010
     *
     * @mbg.generated Tue Oct 30 14:14:52 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wire_attributes_ybt5359_2010.id
     *
     * @return the value of wire_attributes_ybt5359_2010.id
     *
     * @mbg.generated Tue Oct 30 14:14:52 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wire_attributes_ybt5359_2010.id
     *
     * @param id the value for wire_attributes_ybt5359_2010.id
     *
     * @mbg.generated Tue Oct 30 14:14:52 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wire_attributes_ybt5359_2010.structure
     *
     * @return the value of wire_attributes_ybt5359_2010.structure
     *
     * @mbg.generated Tue Oct 30 14:14:52 CST 2018
     */
    public String getStructure() {
        return structure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wire_attributes_ybt5359_2010.structure
     *
     * @param structure the value for wire_attributes_ybt5359_2010.structure
     *
     * @mbg.generated Tue Oct 30 14:14:52 CST 2018
     */
    public void setStructure(String structure) {
        this.structure = structure == null ? null : structure.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wire_attributes_ybt5359_2010.minimum_breaking_force
     *
     * @return the value of wire_attributes_ybt5359_2010.minimum_breaking_force
     *
     * @mbg.generated Tue Oct 30 14:14:52 CST 2018
     */
    public Double getMinimumBreakingForce() {
        return minimumBreakingForce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wire_attributes_ybt5359_2010.minimum_breaking_force
     *
     * @param minimumBreakingForce the value for wire_attributes_ybt5359_2010.minimum_breaking_force
     *
     * @mbg.generated Tue Oct 30 14:14:52 CST 2018
     */
    public void setMinimumBreakingForce(Double minimumBreakingForce) {
        this.minimumBreakingForce = minimumBreakingForce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wire_attributes_ybt5359_2010.tanning_loss_factor
     *
     * @return the value of wire_attributes_ybt5359_2010.tanning_loss_factor
     *
     * @mbg.generated Tue Oct 30 14:14:52 CST 2018
     */
    public Double getTanningLossFactor() {
        return tanningLossFactor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wire_attributes_ybt5359_2010.tanning_loss_factor
     *
     * @param tanningLossFactor the value for wire_attributes_ybt5359_2010.tanning_loss_factor
     *
     * @mbg.generated Tue Oct 30 14:14:52 CST 2018
     */
    public void setTanningLossFactor(Double tanningLossFactor) {
        this.tanningLossFactor = tanningLossFactor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wire_attributes_ybt5359_2010.partial_intensity_low
     *
     * @return the value of wire_attributes_ybt5359_2010.partial_intensity_low
     *
     * @mbg.generated Tue Oct 30 14:14:52 CST 2018
     */
    public Integer getPartialIntensityLow() {
        return partialIntensityLow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wire_attributes_ybt5359_2010.partial_intensity_low
     *
     * @param partialIntensityLow the value for wire_attributes_ybt5359_2010.partial_intensity_low
     *
     * @mbg.generated Tue Oct 30 14:14:52 CST 2018
     */
    public void setPartialIntensityLow(Integer partialIntensityLow) {
        this.partialIntensityLow = partialIntensityLow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wire_attributes_ybt5359_2010.partial_reverse_low
     *
     * @return the value of wire_attributes_ybt5359_2010.partial_reverse_low
     *
     * @mbg.generated Tue Oct 30 14:14:52 CST 2018
     */
    public Integer getPartialReverseLow() {
        return partialReverseLow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wire_attributes_ybt5359_2010.partial_reverse_low
     *
     * @param partialReverseLow the value for wire_attributes_ybt5359_2010.partial_reverse_low
     *
     * @mbg.generated Tue Oct 30 14:14:52 CST 2018
     */
    public void setPartialReverseLow(Integer partialReverseLow) {
        this.partialReverseLow = partialReverseLow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wire_attributes_ybt5359_2010.intensity_low
     *
     * @return the value of wire_attributes_ybt5359_2010.intensity_low
     *
     * @mbg.generated Tue Oct 30 14:14:52 CST 2018
     */
    public Integer getIntensityLow() {
        return intensityLow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wire_attributes_ybt5359_2010.intensity_low
     *
     * @param intensityLow the value for wire_attributes_ybt5359_2010.intensity_low
     *
     * @mbg.generated Tue Oct 30 14:14:52 CST 2018
     */
    public void setIntensityLow(Integer intensityLow) {
        this.intensityLow = intensityLow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wire_attributes_ybt5359_2010.reverse_low
     *
     * @return the value of wire_attributes_ybt5359_2010.reverse_low
     *
     * @mbg.generated Tue Oct 30 14:14:52 CST 2018
     */
    public Integer getReverseLow() {
        return reverseLow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wire_attributes_ybt5359_2010.reverse_low
     *
     * @param reverseLow the value for wire_attributes_ybt5359_2010.reverse_low
     *
     * @mbg.generated Tue Oct 30 14:14:52 CST 2018
     */
    public void setReverseLow(Integer reverseLow) {
        this.reverseLow = reverseLow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wire_attributes_ybt5359_2010.twist_distance
     *
     * @return the value of wire_attributes_ybt5359_2010.twist_distance
     *
     * @mbg.generated Tue Oct 30 14:14:52 CST 2018
     */
    public Double getTwistDistance() {
        return twistDistance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wire_attributes_ybt5359_2010.twist_distance
     *
     * @param twistDistance the value for wire_attributes_ybt5359_2010.twist_distance
     *
     * @mbg.generated Tue Oct 30 14:14:52 CST 2018
     */
    public void setTwistDistance(Double twistDistance) {
        this.twistDistance = twistDistance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wire_attributes_ybt5359_2010.state
     *
     * @return the value of wire_attributes_ybt5359_2010.state
     *
     * @mbg.generated Tue Oct 30 14:14:52 CST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wire_attributes_ybt5359_2010.state
     *
     * @param state the value for wire_attributes_ybt5359_2010.state
     *
     * @mbg.generated Tue Oct 30 14:14:52 CST 2018
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wire_attributes_ybt5359_2010
     *
     * @mbg.generated Tue Oct 30 14:14:52 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", structure=").append(structure);
        sb.append(", minimumBreakingForce=").append(minimumBreakingForce);
        sb.append(", tanningLossFactor=").append(tanningLossFactor);
        sb.append(", partialIntensityLow=").append(partialIntensityLow);
        sb.append(", partialReverseLow=").append(partialReverseLow);
        sb.append(", intensityLow=").append(intensityLow);
        sb.append(", reverseLow=").append(reverseLow);
        sb.append(", twistDistance=").append(twistDistance);
        sb.append(", state=").append(state);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}