package com.hbsi.domain;

import java.io.Serializable;

public class FromValue implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column from_value.id
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column from_value.standard_num
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    private String standardNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column from_value.rated_strength
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    private String ratedStrength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column from_value.surface_state
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    private String surfaceState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column from_value.twisting_method
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    private String twistingMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column from_value.state
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table from_value
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column from_value.id
     *
     * @return the value of from_value.id
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column from_value.id
     *
     * @param id the value for from_value.id
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column from_value.standard_num
     *
     * @return the value of from_value.standard_num
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public String getStandardNum() {
        return standardNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column from_value.standard_num
     *
     * @param standardNum the value for from_value.standard_num
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public void setStandardNum(String standardNum) {
        this.standardNum = standardNum == null ? null : standardNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column from_value.rated_strength
     *
     * @return the value of from_value.rated_strength
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public String getRatedStrength() {
        return ratedStrength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column from_value.rated_strength
     *
     * @param ratedStrength the value for from_value.rated_strength
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public void setRatedStrength(String ratedStrength) {
        this.ratedStrength = ratedStrength == null ? null : ratedStrength.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column from_value.surface_state
     *
     * @return the value of from_value.surface_state
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public String getSurfaceState() {
        return surfaceState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column from_value.surface_state
     *
     * @param surfaceState the value for from_value.surface_state
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public void setSurfaceState(String surfaceState) {
        this.surfaceState = surfaceState == null ? null : surfaceState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column from_value.twisting_method
     *
     * @return the value of from_value.twisting_method
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public String getTwistingMethod() {
        return twistingMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column from_value.twisting_method
     *
     * @param twistingMethod the value for from_value.twisting_method
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public void setTwistingMethod(String twistingMethod) {
        this.twistingMethod = twistingMethod == null ? null : twistingMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column from_value.state
     *
     * @return the value of from_value.state
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column from_value.state
     *
     * @param state the value for from_value.state
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table from_value
     *
     * @mbg.generated Wed Sep 26 15:54:22 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", standardNum=").append(standardNum);
        sb.append(", ratedStrength=").append(ratedStrength);
        sb.append(", surfaceState=").append(surfaceState);
        sb.append(", twistingMethod=").append(twistingMethod);
        sb.append(", state=").append(state);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}